[heartbeat]
command:/usr/local/libexec/ggernaut-status/status-run-reporter /usr/local/etc/ggernaut-status/host.env host
parameters:
type:script
message:Sending Ggernaut status heartbeat
description:Ggernaut status heartbeat
